name: flutter_dialpad
description: A phone dialer widget that can be added to any Flutter Application to enable ability to dial a number. This could be combined with a voip application to enable placing calls.
version: 1.1.0
homepage: "https://www.eopeter.com"
repository: "https://github.com/eopeter/flutter_dialpad"
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

#  flutter_dtmf: ^2.0.2
  flutter_masked_text2: ^0.9.1
  #auto_size_text: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter